### ISSUE TITLE
Won't compile with boost version 1.58

### ISSUE THREAD

**Issue by xaedes** [ros-industrial/ros_canopen#177]
On my system I can't compile canopen_chain_node with boos version 1.58

Boost-Version:

```
dpkg -S /usr/include/boost/version.hpp 
libboost1.58-dev:amd64: /usr/include/boost/version.hpp
```

Compile-Error:

```
In file included from /home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:3:0:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/include/canopen_chain_node/ros_chain.h:155:12: error: ‘scoped_ptr’ in namespace ‘boost’ does not name a template type
     boost::scoped_ptr<boost::thread> thread_;
            ^
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp: In member function ‘virtual bool canopen::RosChain::handle_init(std_srvs::Trigger::Request&, std_srvs::Trigger::Response&)’:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:80:5: error: ‘thread_’ was not declared in this scope
     thread_.reset(new boost::thread(&RosChain::run, this));
     ^
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp: In member function ‘virtual bool canopen::RosChain::handle_recover(std_srvs::Trigger::Request&, std_srvs::Trigger::Response&)’:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:118:24: error: ‘thread_’ was not declared in this scope
     if(initialized_ && thread_){
                        ^
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp: In member function ‘virtual void canopen::RosChain::handleShutdown(canopen::LayerStatus&)’:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:156:25: error: ‘thread_’ was not declared in this scope
     if(initialized_ &&  thread_){
                         ^
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp: In member function ‘virtual bool canopen::RosChain::handle_shutdown(std_srvs::Trigger::Request&, std_srvs::Trigger::Response&)’:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:168:24: error: ‘thread_’ was not declared in this scope
     if(initialized_ && thread_){
                        ^
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp: In member function ‘void canopen::RosChain::report_diagnostics(diagnostic_updater::DiagnosticStatusWrapper&)’:
/home/xaedes/gits/fahrrad/workspace/src/canopen_chain_node/src/ros_chain.cpp:455:15: error: ‘thread_’ was not declared in this scope
     }else if(!thread_){
               ^
canopen_chain_node/CMakeFiles/canopen_ros_chain.dir/build.make:62: recipe for target 'canopen_chain_node/CMakeFiles/canopen_ros_chain.dir/src/ros_chain.cpp.o' failed
make[2]: *** [canopen_chain_node/CMakeFiles/canopen_ros_chain.dir/src/ros_chain.cpp.o] Error 1
CMakeFiles/Makefile2:7509: recipe for target 'canopen_chain_node/CMakeFiles/canopen_ros_chain.dir/all' failed
make[1]: *** [canopen_chain_node/CMakeFiles/canopen_ros_chain.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

I googled and found someone with a similar issue on another project:
https://github.com/OpenImageIO/oiio/issues/1024

The way they solved it (adding `#include <boost/scoped_ptr.hpp>` in `canopen_chain_node/include/canopen_chain_node/ros_chain`) also worked for me. 
I make a pull request with that change.

**Comment by mathias-luedtke** [comment]
Good point!
I wonder which header pulled in the `scoped_ptr` in boost 1.54.
